// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Haack.Encourage.x64
{
    internal sealed partial class Vsix
    {
        public const string Id = "66C43F9C-C61A-4F7C-A91E-0419ABAA611B";
        public const string Name = "Encourage-22";
        public const string Description = @"Adds a bit of whimsy to your work day.";
        public const string Language = "en-US";
        public const string Version = "1.5.0";
        public const string Author = "Haacked";
        public const string Tags = "fun";
    }
}
