// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Haack.Encourage.x64
{
    internal sealed partial class Vsix
    {
        public const string Id = "4A15F36D-0769-4479-AEC4-56BF2FF8EF86";
        public const string Name = "Encourage";
        public const string Description = @"Adds a bit of whimsy to your work day.";
        public const string Language = "en-US";
        public const string Version = "1.2.2";
        public const string Author = "Phil Haack";
        public const string Tags = "fun";
    }
}
