// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Haack.Encourage.x86
{
    internal sealed partial class Vsix
    {
        public const string Id = "f38d29e7-cd86-43d5-9c32-4be26302b55e";
        public const string Name = "Encourage";
        public const string Description = @"Adds a bit of whimsy to your work day.";
        public const string Language = "en-US";
        public const string Version = "1.5.0";
        public const string Author = "Phil Haack";
        public const string Tags = "fun";
    }
}
